LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

# Default to the AIDL 1.0 implementation
TARGET_POWERHAL_AIDL_VERSION ?= 1

LOCAL_MODULE := android.hardware.power-service-mediatek
LOCAL_MODULE_RELATIVE_PATH := hw
LOCAL_MODULE_TAGS  := optional
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/vendor_overlay/$(PRODUCT_EXTRA_VNDK_VERSIONS)/lib64
LOCAL_REQUIRED_MODULES := power-mtk-v$(TARGET_POWERHAL_AIDL_VERSION).xml
LOCAL_MULTILIB := 64
LOCAL_SRC_FILES := Power.cpp

LOCAL_SHARED_LIBRARIES := \
    libbase \
    libbinder_ndk \
    libpowerhal \
    android.hardware.power-V$(TARGET_POWERHAL_AIDL_VERSION)-ndk_platform

LOCAL_CFLAGS += -DPOWERHAL_AIDL_VERSION=$(TARGET_POWERHAL_AIDL_VERSION)

ifneq ($(TARGET_TAP_TO_WAKE_NODE),)
    LOCAL_CFLAGS += -DTAP_TO_WAKE_NODE=\"$(TARGET_TAP_TO_WAKE_NODE)\"
endif

ifneq ($(TARGET_POWERHAL_MODE_EXT),)
    LOCAL_CFLAGS += -DMODE_EXT
    LOCAL_SRC_FILES += ../../../$(TARGET_POWERHAL_MODE_EXT)
endif

include $(BUILD_SHARED_LIBRARY)
include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_MODULE := power-mtk-v$(TARGET_POWERHAL_AIDL_VERSION).xml
LOCAL_SRC_FILES := $(LOCAL_MODULE)
LOCAL_MODULE_TAGS  := optional
LOCAL_MODULE_CLASS := ETC
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/vendor_overlay/$(PRODUCT_EXTRA_VNDK_VERSIONS)/etc/vintf/manifest
include $(BUILD_PREBUILT)
